Repository Gismo1337/vue-cookie-consent-banner, pull requests merged in 2022-10, with the labels that each got.

#5 chore: code formatting with prettier
  README.md
  package.json
  src/App.vue
  src/assets/base.css
  src/components/CookieModal.vue
  src/install.js
  src/main.js
  vite.config.js
Labels: hacktoberfest, hacktoberfest-accepted

#8 Added CONTRIBUTING.md
  CONTRIBUTING.md
Labels: hacktoberfest-accepted

#10 Added CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: documentation, good first issue, hacktoberfest, hacktoberfest-accepted

#11 chore: fix css issues
  src/App.vue
  src/components/CookieModal.vue
Labels: bug, hacktoberfest, hacktoberfest-accepted

#14 Create LICENSE.md
  LICENSE.md
Labels: hacktoberfest, hacktoberfest-accepted

#15 updated README.md
  README.md
Labels: hacktoberfest, hacktoberfest-accepted

#16 Save user preferences to cookie
  src/components/CookieModal.vue
Labels: hacktoberfest, hacktoberfest-accepted

#17 feat: prevent scroll before consent choice
  src/App.vue
  src/components/CookieModal.vue
Labels: hacktoberfest, hacktoberfest-accepted

#19 Fix: Write a issue template
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: documentation, hacktoberfest, hacktoberfest-accepted

#24 Feature: Change close X Icon to a svg file, Adds FontAwesome Library
  src/components/CookieModal.vue
Labels: hacktoberfest, hacktoberfest-accepted

#27 create checkbox transition
  src/components/AppCheck.vue
  src/components/CookieModal.vue
Labels: hacktoberfest, hacktoberfest-accepted

#33 npm files
  .gitignore
  dist/demo.html
  dist/vue-hello-world-simple.common.js
  dist/vue-hello-world-simple.common.js.map
  dist/vue-hello-world-simple.css
  dist/vue-hello-world-simple.umd.js
  dist/vue-hello-world-simple.umd.js.map
  dist/vue-hello-world-simple.umd.min.js
  dist/vue-hello-world-simple.umd.min.js.map
  package.json
Labels: hacktoberfest, hacktoberfest-accepted

#32 Create pull_request_template.md
  .github/pull_request_template.md
Labels: hacktoberfest, hacktoberfest-accepted

#35 Bad link to pull requests page rectified
  .github/pull_request_template.md
Labels: hacktoberfest, hacktoberfest-accepted

#37 Added toggleScroll emit to define
  src/components/CookieModal.vue
Labels: hacktoberfest, hacktoberfest-accepted

#41 Fixes #2 : Write Checkbox Subtext to explain cookie
  src/components/CookieModal.vue
Labels: hacktoberfest, hacktoberfest-accepted

#44 Noscript error and some changes
  index.html
  package-lock.json
  src/components/CookieModal.vue
Labels: hacktoberfest, hacktoberfest-accepted

#45 Fixed the modal Width
  src/components/CookieModal.vue
Labels: hacktoberfest, hacktoberfest-accepted

#52 [Bug] Cookie name and subtext are not clickable #51 resolving
  src/components/CookieModal.vue
Labels: hacktoberfest, hacktoberfest-accepted

#53 Create Option Section Component
  src/components/CookieModal.vue
  src/components/OptionSection.vue
Labels: hacktoberfest, hacktoberfest-accepted

#55 checkbox styling
  src/components/OptionSection.vue
Labels: bug, hacktoberfest, hacktoberfest-accepted

#57 Align X Icon With Title Text
  src/components/CookieModal.vue
Labels: hacktoberfest, hacktoberfest-accepted

#59 new image
  README.md
Labels: hacktoberfest, hacktoberfest-accepted

#60 style: Write a Button Single File Component to upgrade the readability
  src/components/Button.vue
  src/components/FooterSection.vue
Labels: hacktoberfest, hacktoberfest-accepted
